version: "2.1"
jobs:
  simple:
    docker:
      - image: ${EXECUTOR_URI}:latest
    steps:
      - checkout
      - run:
          working_directory: ./examples/simple
          name: terragrunt apply
          command: |
            terragrunt init --terragrunt-non-interactive
            terragrunt apply -auto-approve --terragrunt-non-interactive 2>&1 | tee /tmp/apply.log
      - run:
          name: terragrunt state pull
          working_directory: ./examples/simple
          command: |
            terragrunt state pull --terragrunt-non-interactive > /tmp/terraform.tfstate
      - run:
          name: Test
          command: |
            cat /tmp/terraform.tfstate | grep -q stateless-ssm-parameters-demo-aws-access-key-id
            cat /tmp/apply.log | grep -q stateless-ssm-parameters-demo-aws-access-key-id
            cat /tmp/terraform.tfstate > /tmp/combined.txt
            cat /tmp/apply.log >> /tmp/combined.txt
            cat /tmp/combined.txt | grep -qv AKIAIOSFODNN7EXAMPLE
workflows:
  simple:
    jobs:
      - simple
